### PR TITLE
noun URLs, error UI; Code style: ocap, airbnb

### PR DESCRIPTION
**Pull request by dckc**

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
This looks good and I'll merger it. Wouldn't mind talking it through first though. I'm glad you ditched jquery! I'm unclear about the use of `const` for the port and host. I thought you were saying `const`s should be design time constants. The the ports are specified by the user at runtime.

**Comment by dckc** [comment]
consts should be const in the scope where they are declared. So module level consts should be design-time constants.

**Comment by dckc** [comment]
Umm... this code doesn't actually work. :)

Stay tuned.

**Comment by dckc** [comment]
Seems to work pretty well now.

**Pull request merged**
